export const Tiles = {
  wall: 'x',
  wallHorizontal: '=',
  wallVertical: '|',
  point: '.',
  withoutPoint: '_',
  power: 'O',
  pacman: 'P',
  ghostGate: '-',
  teleportRight: '>',
  teleportLeft: '<',
  ghost1: '1',
  ghost2: '2',
  ghost3: '3',
  ghost4: '4',
} as const;